name: Build qBittorrent static

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git cmake wget

    - name: Build and install Zlib
      run: |
        wget -q https://zlib.net/zlib-1.3.1.tar.gz
        tar -xzf zlib-1.3.1.tar.gz
        cd zlib-1.3.1
        ./configure --static
        make -j$(nproc)
        sudo make install

    - name: Build and install OpenSSL
      run: |
        wget -q https://www.openssl.org/source/openssl-3.3.2.tar.gz
        tar -xzf openssl-3.3.2.tar.gz
        cd openssl-3.3.2
        ./config no-shared --prefix=/usr/local/openssl
        make -j$(nproc)
        sudo make install

    - name: Build and install Boost
      run: |
        wget -q https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
        tar -xzf boost_1_81_0.tar.gz
        cd boost_1_81_0
        ./bootstrap.sh
        sudo cp b2 /usr/bin
        ./b2  clean
        sudo ./b2  link=static runtime-link=static install --prefix=/usr/local/boost

    - name: Build and install libtorrent
      run: |
        git clone --recursive https://github.com/arvidn/libtorrent.git
        cd libtorrent
        # git checkout libtorrent-2.0.10  # Укажите нужную версию
        # ./autotool.sh
        #./configure --enable-static --disable-shared --with-boost=/usr/local/boost
        sudo b2 install --prefix=/usr/local/libtorrent
        make -j$(nproc)
        sudo make install

    - name: Build and install GeoIP
      run: |
        wget https://github.com/maxmind/GeoIP2-City/releases/download/v2.0.0/GeoIP2-City.tar.gz
        tar -xzf GeoIP2-City.tar.gz
        cd GeoIP2-City
        ./configure --enable-static --disable-shared
        make -j$(nproc)
        sudo make install

    - name: Build and install Qt 6 statically
      run: |
        wget https://download.qt.io/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz
        tar -xf qt-everywhere-src-6.5.3.tar.xz
        cd qt-everywhere-src-6.5.3
        ./configure -static -release -prefix /usr/local/qt6 -opensource -confirm-license -nomake examples -nomake tests
        make -j$(nproc)
        sudo make install

    - name: Build qBittorrent
      run: |
        mkdir build
        cd build
        qmake "CONFIG+=static" ..
        make -j$(nproc)

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent
        path: build/qbittorrent

